# Generated by Django 5.1.6 on 2025-03-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.CharField(
                choices=[
                    ("12:00:00", "12:00 PM"),
                    ("14:00:00", "3:00 PM"),
                    ("16:00:00", "6:00 PM"),
                    ("18:00:00", "9:00 PM"),
                ],
                max_length=8,
            ),
        ),
    ]
